import { Check, Droplet, Loader2, Sparkles, Sun, Waves } from "lucide-react";

const icons = { Cleanse: Waves, Hydrate: Droplet, Moisturize: Sparkles, "Sun Protection": Sun };
const isCleanse = (step) => step.title.trim().toLowerCase() === "cleanse";
const displayTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;

export default function RoutineTracker({ steps, phase, currentStep, remaining, onConfirmCleansing, onStartSession }) {
  const timedSteps = steps.filter((step) => !isCleanse(step));
  const percent = phase === "complete" ? 100 : timedSteps.length ? Math.round((timedSteps.filter((step) => step.complete).length / timedSteps.length) * 100) : 0;
  return <section className="rounded-3xl panel-quiet shadow-quiet p-6 md:p-7">
    <div className="flex items-center justify-between"><div><p className="font-display text-lg font-semibold tracking-tight">Today's Skincare Routine</p><p className="mt-1 text-xs text-ink-400">Each session starts fresh; your products stay in your routine.</p></div><span className="font-mono text-sm text-cyan-300">{percent}%</span></div>
    <div className="mb-6 mt-4 h-1.5 overflow-hidden rounded-full bg-base-700"><div className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-azure-500 transition-all duration-500" style={{ width: `${percent}%` }} /></div>
    {!steps.length ? <p className="text-sm text-ink-400">Loading skincare routine…</p> : <ol className="space-y-2">{steps.map((step) => { const Icon = icons[step.title] || Sparkles; const manual = isCleanse(step); const active = currentStep?.id === step.id && (phase === "preparing" || phase === "running" || phase === "paused"); const done = step.complete || (manual && !["not_started", "cleansing"].includes(phase)); return <li key={step.id} className={`rounded-2xl border p-4 ${active ? "border-cyan-400/40 bg-cyan-400/5" : "border-line bg-base-900/30"}`}><div className="flex gap-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border ${done ? "border-moss-400/40 bg-moss-400/15 text-moss-400" : "border-line text-ink-400"}`}>{done ? <Check size={14} /> : <Icon size={14} />}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium"><span className="mr-2 font-mono text-ink-500">{String(step.id).padStart(2, "0")}</span>{step.title}</p><span className="font-mono text-[11px] text-ink-500">{manual ? "Manual preparation" : step.duration}</span></div><p className="mt-1 text-xs leading-relaxed text-ink-400">{manual ? "Clean your face and come back." : step.description}</p>{manual && phase === "cleansing" && <button onClick={onConfirmCleansing} className="mt-3 rounded-xl bg-gradient-to-r from-cyan-500 to-azure-500 px-4 py-2 text-sm font-medium text-base-950 focus-ring">I've Cleaned My Face</button>}</div></div></li>; })}</ol>}
    <div className="mt-5 rounded-2xl border border-line bg-base-900/50 p-4 text-center">{phase === "not_started" ? <><p className="font-display text-base font-semibold">Ready for your skincare routine?</p><button onClick={onStartSession} className="mt-3 rounded-xl bg-gradient-to-r from-cyan-500 to-azure-500 px-4 py-2 text-sm font-medium text-base-950 focus-ring">Start Routine</button></> : phase === "analyzing" ? <><Loader2 className="mx-auto animate-spin text-cyan-400" size={20} /><p className="mt-2 font-medium">Analyzing your skin…</p></> : phase === "preparing" ? <><p className="font-display text-base font-semibold">Get Ready for {currentStep?.title}</p><p className="mt-3 font-mono text-3xl text-cyan-300">{displayTime(remaining)}</p></> : phase === "running" || phase === "paused" ? <><p className="font-display text-base font-semibold">{phase === "paused" ? "PAUSED" : currentStep?.title}</p>{phase === "paused" && <p className="mt-1 font-medium">{currentStep?.title}</p>}<p className="mt-1 text-xs text-ink-400">{phase === "preparing" ? "Preparation countdown" : "Time remaining"}</p><p className="mt-2 font-mono text-3xl text-cyan-300">{displayTime(remaining)}</p></> : phase === "complete" ? <><p className="font-display text-base font-semibold text-moss-400">Skincare Routine Complete ✓</p><button onClick={onStartSession} className="mt-3 rounded-xl bg-gradient-to-r from-cyan-500 to-azure-500 px-4 py-2 text-sm font-medium text-base-950 focus-ring">Start Routine Again</button></> : <p className="text-sm text-ink-300">Clean your face and come back. There is no timer for cleansing.</p>}</div>
  </section>;
}
