import { useCallback, useEffect, useState } from "react";
import { ExternalLink, Plus, Trash2, X } from "lucide-react";
import { addProductToRoutine, getDemoProductRecommendations, getProductRecommendations, getRoutineProducts, removeRoutineProduct } from "../services/mira.js";

const labels = { CLEANSE: "Cleanse", HYDRATE: "Hydrate", TREATMENT: "Treatment", MOISTURIZE: "Moisturize", SUN_PROTECTION: "Sun Protection" };
function ProductCard({ product, onAdd, demo }) {
  const [details, setDetails] = useState(false);
  return <article className="rounded-2xl border border-line bg-base-900/60 p-4"><div className="flex gap-3">
    {product.image_url ? <img src={product.image_url} alt="" className="h-16 w-16 rounded-xl object-cover bg-base-800" /> : <div className="h-16 w-16 rounded-xl bg-base-800 text-xs text-ink-500 grid place-items-center">No image</div>}
    <div className="min-w-0"><p className="font-medium text-sm">{product.name}</p><p className="text-xs text-ink-400">{product.brand || "Brand unavailable"}</p><p className="mt-1 text-[11px] text-cyan-300">{product.category.replaceAll("_", " ")} · {labels[product.routine_step]}</p></div></div>
    {product.why && <p className="mt-3 text-xs text-ink-300">{product.why}</p>}
    {details && <div className="mt-3 border-t border-line pt-3 text-xs text-ink-400 space-y-1"><p>Ingredients: {product.ingredients || "Not available"}</p><p>Labels: {product.labels || "Not available"}</p><p>Barcode: {product.barcode || "Not available"}</p><p>Product information sourced from Open Beauty Facts.</p></div>}
    <div className="mt-4 flex gap-2"><button onClick={() => setDetails(!details)} className="rounded-lg border border-line px-3 py-1.5 text-xs">{details ? "Hide Details" : "View Details"}</button>{product.product_url && <a className="rounded-lg border border-line px-2 py-1.5 text-xs" href={product.product_url} target="_blank" rel="noreferrer"><ExternalLink size={14}/></a>}<button onClick={() => onAdd(product)} className="ml-auto inline-flex items-center gap-1 rounded-lg bg-cyan-400 px-3 py-1.5 text-xs font-semibold text-base-950"><Plus size={14}/> {demo ? "Login to Save" : "Add"}</button></div>
  </article>;
}
export default function ProductsPage({ demo = false, onNavigate }) {
  const [data, setData] = useState(null), [routine, setRoutine] = useState([]), [error, setError] = useState(""), [confirm, setConfirm] = useState(null), [notice, setNotice] = useState("");
  const load = useCallback(async () => { setError(""); try { if (demo) { setData(await getDemoProductRecommendations()); setRoutine([]); } else { const [recommendations, saved] = await Promise.all([getProductRecommendations(), getRoutineProducts()]); setData(recommendations); setRoutine(saved); } } catch (e) { setError(e.message || "Product service temporarily unavailable."); } }, [demo]);
  useEffect(() => { load(); }, [load]);
  const add = async () => { if (demo) { onNavigate("login"); return; } try { const saved = await addProductToRoutine(confirm); setRoutine((rows) => [...rows, saved]); setNotice(`✓ Added to ${labels[saved.routine_step]}`); setConfirm(null); } catch (e) { setNotice(e.message || "Could not add product."); setConfirm(null); } };
  const remove = async (id) => { try { await removeRoutineProduct(id); setRoutine((rows) => rows.filter((r) => r.id !== id)); } catch (e) { setNotice(e.message); } };
  return <div className="space-y-6">{error ? <section className="rounded-3xl panel-quiet p-6 text-amber-400">{error}</section> : !data ? <section className="rounded-3xl panel-quiet p-6 text-ink-400">Run a {demo ? "demo " : ""}skin scan to see products.</section> : <><section className="rounded-3xl panel-quiet p-6"><h2 className="font-display text-xl font-semibold">MIRA Product Recommendations</h2><p className="mt-2 text-sm text-ink-400">{data.summary}</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.items.length ? data.items.map((p) => <ProductCard key={p.product_id} product={p} onAdd={setConfirm} demo={demo}/>) : <p className="text-sm text-ink-400">No matching products found.</p>}</div></section><section className="rounded-3xl panel-quiet p-6"><h2 className="font-display text-xl font-semibold">More Products You May Like</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.more.map((p) => <ProductCard key={p.product_id} product={p} onAdd={setConfirm} demo={demo}/>)}</div></section></>}
  {!demo && <section className="rounded-3xl panel-quiet p-6"><h2 className="font-display text-xl font-semibold">My Skincare Routine</h2>{Object.entries(labels).map(([step, title]) => { const rows = routine.filter((p) => p.routine_step === step); return rows.length ? <div key={step} className="mt-4"><p className="text-sm text-cyan-300">{title}</p>{rows.map((p) => <div className="mt-2 flex items-center justify-between rounded-xl border border-line p-3 text-sm" key={p.id}><span>{p.name}</span><button onClick={() => remove(p.id)} className="text-ink-400 hover:text-coral-400" aria-label={`Remove ${p.name}`}><Trash2 size={15}/></button></div>)}</div> : null; })}</section>}
  {notice && <p className="text-center text-sm text-moss-400">{notice}</p>}{confirm && <div className="fixed inset-0 z-50 grid place-items-center bg-base-950/70 p-4"><div className="w-full max-w-sm rounded-2xl panel-quiet p-6"><button onClick={() => setConfirm(null)} className="float-right"><X size={16}/></button><p className="font-semibold">{demo ? `Login to save ${confirm.name}?` : `Add ${confirm.name} to your routine?`}</p><p className="mt-2 text-sm text-ink-400">{demo ? "Demo products are never saved to a personal routine." : `Routine step: ${labels[confirm.routine_step]}`}</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setConfirm(null)} className="rounded-lg border border-line px-3 py-2 text-sm">Cancel</button><button onClick={add} className="rounded-lg bg-cyan-400 px-3 py-2 text-sm font-semibold text-base-950">{demo ? "Login to Save" : "Add to Routine"}</button></div></div></div>}</div>;
}
